Add room config utilities
FindHotel/redshift-udfs pull request #6
Opened 2017-06-26 23:39 UTC by CanCeylan

This PR adds two UDF utilities which return the number of adults and children for a given room configuration string.

2017-06-27 14:18 UTC, germangh requested changes

2017-06-27 14:18 UTC, germangh commented on lib/udf_string_utils.rb
> +          type:        :function,
There is a lot of duplication between two UDFs. I would just create one UDF (e.g. `parse_room_description`) that takes two parameters:

* `component`: a string with the component you want the UDF to return. E.g. `adults`, `children`, `rooms`.
* `room`: the room description

I would also have that order for the parameters so emulate Redshift built-in functions such as `date_part` or `date_trunc`.

And a general comment. I wouldn't add this utility to the `udf_string_utils.rb` module. Instead I would create a new module and call it `udf_findhotel.rb` which we could use for utilities that are very specific to FindHotel.

2017-06-27 22:55 UTC, CanCeylan commented on lib/udf_string_utils.rb
> +          type:        :function,
Thanks for the comments. I now created a new file called `udf_findhotel_utils.rb`. And defined only one function in there. I also added `UdfFindhotelUtils::UDFS,` line in `udf_harness.rb` file's `initialize` method. But when I try to run tests it always give the following error:

 `<class:UdfFindhotelUtils>': uninitialized constant UdfFindhotelUtils::None (NameError)`

Any suggestions?

2017-06-28 04:55 UTC, germangh commented on lib/udf_string_utils.rb
> +          type:        :function,
Push your changes to the remote and I can take a look, there must be something wrong in your code because what say you did should be enough.

2017-06-28 16:07 UTC, acharp commented on lib/udf_string_utils.rb
> +          type:        :function,
@CanCeylan I have checked your code and it looks perfectly fine. Let me know if you are still having the issue I'll pull the branch and debug it more thoroughly.

2017-06-29 17:26 UTC, acharp commented
@CanCeylan It's working now. There were two problems :
- In the tests the  `None` value for the field `expected` has to be written as `nil` in ruby
- A few syntax errors here and there, check my commit to see them

2017-06-29 17:31 UTC, merged